# Generated by Django 6.1.1 on 2026-10-04 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kompaniya nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logotip')),
                ('description', models.TextField(verbose_name='Kompaniya haqida')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Veb-sayt')),
                ('location', models.CharField(max_length=100, verbose_name='Joylashuv/Shahar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Egasining profili')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Vakansiya nomi')),
                ('description', models.TextField(verbose_name='Tavsif va talablar')),
                ('location', models.CharField(max_length=100, verbose_name='Joylashuv')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min maosh ($)')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max maosh ($)')),
                ('technologies', models.CharField(help_text="Skill Match uchun kalit so'zlar (masalan: Python, Django, PostgreSQL)", max_length=255, verbose_name='Talab qilinadigan texnologiyalar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company', verbose_name='Kompaniya')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kasb unvoni (Masalan: Python Backend Developer)')),
                ('bio', models.TextField(blank=True, verbose_name="O'zi haqida qisqacha")),
                ('skills', models.CharField(help_text='Vergul bilan ajratib yozing (masalan: Python, Django, PostgreSQL)', max_length=255, verbose_name="Ko'nikmalar")),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Tajriba (yillar)')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='PDF Rezyume fayli')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
    ]
