# Generated by Django 6.1.1 on 2026-10-05 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='bi-briefcase', help_text='Bootstrap icon klassi (masalan: bi-code-slash)', max_length=50)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Kompaniya', 'verbose_name_plural': 'Kompaniyalar'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vakansiya', 'verbose_name_plural': 'Vakansiyalar'},
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', "To'liq stavka (Full-time)"), ('part_time', 'Yarim stavka (Part-time)'), ('remote', 'Masofaviy (Remote)'), ('freelance', 'Frilans (Freelance)'), ('internship', 'Amaliyot (Internship)')], default='full_time', max_length=20, verbose_name='Ish turi'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.category', verbose_name='Kategoriya'),
        ),
    ]
