# Generated by Django 6.1.1 on 2026-10-04 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism-sharif")),
                ('title', models.CharField(max_length=255, verbose_name="Mutaxassislik / Kasb yo'nalishi")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yashash manzili')),
                ('bio', models.TextField(blank=True, null=True, verbose_name="O'zim haqimda")),
                ('skills', models.CharField(blank=True, help_text='Masalan: Python, Django, HTML, CSS, Git', max_length=500, null=True, verbose_name="Ko'nikmalar")),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Tajriba (yillar)')),
                ('education', models.TextField(blank=True, null=True, verbose_name="Ma'lumoti / Ta'lim")),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Ish tajribasi')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='PDF Rezyume fayli')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='GitHub profili')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='LinkedIn profili')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
    ]
